apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-apps
  namespace: argocd
spec:
  project: team-a
  source:
    repoURL: https://github.com/mmastersvz/platform-gitops.git
    targetRevision: HEAD
    path: apps/team-a-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: team-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-b-apps
  namespace: argocd
spec:
  project: team-b
  source:
    repoURL: https://github.com/mmastersvz/platform-gitops.git
    targetRevision: HEAD
    path: apps/team-b-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: team-b
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
