apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/mmastersvz/platform-gitops.git
    targetRevision: HEAD
    path: infrastructure
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
        - /metadata/labels/argocd.argoproj.io~1instance
        - /metadata/annotations/argocd.argoproj.io~1tracking-id
    - group: argoproj.io
      kind: ApplicationSet
      jsonPointers:
        - /status
        - /metadata/labels/argocd.argoproj.io~1instance
        - /metadata/annotations/argocd.argoproj.io~1tracking-id
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
