apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: platform
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.40.9
    helm:
      valuesObject:
        # Optional but recommended customizations
        crds:
          install: true        # Installs CRDs with the chart (default: true)
        controller:
          replicas: 1          # 2 For HA in production
          # logLevel: info
        dashboard:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   # Recommended for CRDs