apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            kargo: enabled
  template:
    metadata:
      name: kargo
    spec:
      project: platform
      destination:
        namespace: kargo
        server: "{{server}}"
      source:
        repoURL: ghcr.io/akuity/kargo-charts
        chart: kargo
        targetRevision: 1.10.0
        helm:
          valuesObject:
            api:
              secret:
                name: kargo-admin-credentials
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
