apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-admin-credentials
  namespace: kargo
  annotations:
    argocd.argoproj.io/sync-wave: "29"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: kargo-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_ACCOUNT_PASSWORD_HASH
      remoteRef:
        key: KARGO_ADMIN_PASSWORD_HASH
    - secretKey: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
      remoteRef:
        key: KARGO_ADMIN_TOKEN_SIGNING_KEY
