apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/mmastersvz/platform-gitops.git
    targetRevision: HEAD
    path: infrastructure/secret-store
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
